version: '3'

services:
  testme:
    build:
      context: .
    container_name: testme-flask-api
    restart: always
    ports:
      - "5011:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./tests:/www/tests
    command: sh -c "python -m flask run --host=0.0.0.0"
